
/* File generated by gen_cfile.py. Should not be modified. */

#include "canopen_master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 canopen_master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 canopen_master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 canopen_master_iam_a_slave = 0;

TIMER_HANDLE canopen_master_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 canopen_master_obj1000 = 0x0;	/* 0 */
                    subindex canopen_master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&canopen_master_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 canopen_master_obj1001 = 0x0;	/* 0 */
                    subindex canopen_master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 canopen_master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t canopen_master_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex canopen_master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&canopen_master_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 canopen_master_obj1005 = 0x0;	/* 0 */
                    ODCallback_t canopen_master_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex canopen_master_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 canopen_master_obj1006 = 0x0;	/* 0 */
                    ODCallback_t canopen_master_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex canopen_master_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 canopen_master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 canopen_master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 canopen_master_obj1014 = 0x80;	/* 128 */
                    subindex canopen_master_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 canopen_master_highestSubIndex_obj1016 = 0;
                    UNS32 canopen_master_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 canopen_master_obj1017 = 0x0;	/* 0 */
                    ODCallback_t canopen_master_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex canopen_master_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&canopen_master_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 canopen_master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 canopen_master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 canopen_master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 canopen_master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex canopen_master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&canopen_master_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&canopen_master_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&canopen_master_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&canopen_master_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x600;	/* 1536 */
                    UNS32 canopen_master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x580;	/* 1408 */
                    UNS8 canopen_master_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 canopen_master_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 canopen_master_obj1281_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex canopen_master_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 canopen_master_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 canopen_master_obj1282_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex canopen_master_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1282 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1282_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1282_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1282_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 canopen_master_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 canopen_master_obj1283_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex canopen_master_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1283 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1283_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1283_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1283_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 canopen_master_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1412 */
                    UNS8 canopen_master_obj1284_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex canopen_master_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1284 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1284_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1284_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1284_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 canopen_master_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 canopen_master_obj1285_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    subindex canopen_master_Index1285[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1285 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1285_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1285_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1285_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1286 :   Client SDO 7 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1286 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1286_COB_ID_Client_to_Server_Transmit_SDO = 0x606;	/* 1542 */
                    UNS32 canopen_master_obj1286_COB_ID_Server_to_Client_Receive_SDO = 0x586;	/* 1414 */
                    UNS8 canopen_master_obj1286_Node_ID_of_the_SDO_Server = 0x6;	/* 6 */
                    subindex canopen_master_Index1286[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1286 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1286_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1286_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1286_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1287 :   Client SDO 8 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1287 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1287_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 canopen_master_obj1287_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 canopen_master_obj1287_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index1287[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1287 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1287_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1287_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1287_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1288 :   Client SDO 9 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1288 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1288_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 canopen_master_obj1288_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 canopen_master_obj1288_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index1288[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1288 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1288_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1288_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1288_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1289 :   Client SDO 10 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj1289 = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj1289_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 canopen_master_obj1289_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 canopen_master_obj1289_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index1289[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj1289 },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1289_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj1289_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj1289_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128A :   Client SDO 11 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj128A = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj128A_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 canopen_master_obj128A_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 canopen_master_obj128A_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index128A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj128A },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128A_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128A_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj128A_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128B :   Client SDO 12 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj128B = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj128B_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 canopen_master_obj128B_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 canopen_master_obj128B_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index128B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj128B },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128B_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128B_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj128B_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128C :   Client SDO 13 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj128C = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj128C_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 canopen_master_obj128C_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 canopen_master_obj128C_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index128C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj128C },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128C_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128C_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj128C_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128D :   Client SDO 14 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj128D = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj128D_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 canopen_master_obj128D_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 canopen_master_obj128D_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index128D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj128D },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128D_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128D_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj128D_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128E :   Client SDO 15 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj128E = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj128E_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 canopen_master_obj128E_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 canopen_master_obj128E_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index128E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj128E },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128E_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128E_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj128E_Node_ID_of_the_SDO_Server }
                     };

/* index 0x128F :   Client SDO 16 Parameter. */
                    UNS8 canopen_master_highestSubIndex_obj128F = 3; /* number of subindex - 1*/
                    UNS32 canopen_master_obj128F_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 canopen_master_obj128F_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 canopen_master_obj128F_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex canopen_master_Index128F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&canopen_master_highestSubIndex_obj128F },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128F_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&canopen_master_obj128F_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&canopen_master_obj128F_Node_ID_of_the_SDO_Server }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable canopen_master_objdict[] = 
{
  { (subindex*)canopen_master_Index1000,sizeof(canopen_master_Index1000)/sizeof(canopen_master_Index1000[0]), 0x1000},
  { (subindex*)canopen_master_Index1001,sizeof(canopen_master_Index1001)/sizeof(canopen_master_Index1001[0]), 0x1001},
  { (subindex*)canopen_master_Index1005,sizeof(canopen_master_Index1005)/sizeof(canopen_master_Index1005[0]), 0x1005},
  { (subindex*)canopen_master_Index1006,sizeof(canopen_master_Index1006)/sizeof(canopen_master_Index1006[0]), 0x1006},
  { (subindex*)canopen_master_Index1014,sizeof(canopen_master_Index1014)/sizeof(canopen_master_Index1014[0]), 0x1014},
  { (subindex*)canopen_master_Index1017,sizeof(canopen_master_Index1017)/sizeof(canopen_master_Index1017[0]), 0x1017},
  { (subindex*)canopen_master_Index1018,sizeof(canopen_master_Index1018)/sizeof(canopen_master_Index1018[0]), 0x1018},
  { (subindex*)canopen_master_Index1280,sizeof(canopen_master_Index1280)/sizeof(canopen_master_Index1280[0]), 0x1280},
  { (subindex*)canopen_master_Index1281,sizeof(canopen_master_Index1281)/sizeof(canopen_master_Index1281[0]), 0x1281},
  { (subindex*)canopen_master_Index1282,sizeof(canopen_master_Index1282)/sizeof(canopen_master_Index1282[0]), 0x1282},
  { (subindex*)canopen_master_Index1283,sizeof(canopen_master_Index1283)/sizeof(canopen_master_Index1283[0]), 0x1283},
  { (subindex*)canopen_master_Index1284,sizeof(canopen_master_Index1284)/sizeof(canopen_master_Index1284[0]), 0x1284},
  { (subindex*)canopen_master_Index1285,sizeof(canopen_master_Index1285)/sizeof(canopen_master_Index1285[0]), 0x1285},
  { (subindex*)canopen_master_Index1286,sizeof(canopen_master_Index1286)/sizeof(canopen_master_Index1286[0]), 0x1286},
  { (subindex*)canopen_master_Index1287,sizeof(canopen_master_Index1287)/sizeof(canopen_master_Index1287[0]), 0x1287},
  { (subindex*)canopen_master_Index1288,sizeof(canopen_master_Index1288)/sizeof(canopen_master_Index1288[0]), 0x1288},
  { (subindex*)canopen_master_Index1289,sizeof(canopen_master_Index1289)/sizeof(canopen_master_Index1289[0]), 0x1289},
  { (subindex*)canopen_master_Index128A,sizeof(canopen_master_Index128A)/sizeof(canopen_master_Index128A[0]), 0x128A},
  { (subindex*)canopen_master_Index128B,sizeof(canopen_master_Index128B)/sizeof(canopen_master_Index128B[0]), 0x128B},
  { (subindex*)canopen_master_Index128C,sizeof(canopen_master_Index128C)/sizeof(canopen_master_Index128C[0]), 0x128C},
  { (subindex*)canopen_master_Index128D,sizeof(canopen_master_Index128D)/sizeof(canopen_master_Index128D[0]), 0x128D},
  { (subindex*)canopen_master_Index128E,sizeof(canopen_master_Index128E)/sizeof(canopen_master_Index128E[0]), 0x128E},
  { (subindex*)canopen_master_Index128F,sizeof(canopen_master_Index128F)/sizeof(canopen_master_Index128F[0]), 0x128F},
};

const indextable * canopen_master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = canopen_master_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = canopen_master_Index1006_callbacks; break;
		case 0x1014: i = 4;break;
		case 0x1017: i = 5;*callbacks = canopen_master_Index1017_callbacks; break;
		case 0x1018: i = 6;break;
		case 0x1280: i = 7;break;
		case 0x1281: i = 8;break;
		case 0x1282: i = 9;break;
		case 0x1283: i = 10;break;
		case 0x1284: i = 11;break;
		case 0x1285: i = 12;break;
		case 0x1286: i = 13;break;
		case 0x1287: i = 14;break;
		case 0x1288: i = 15;break;
		case 0x1289: i = 16;break;
		case 0x128A: i = 17;break;
		case 0x128B: i = 18;break;
		case 0x128C: i = 19;break;
		case 0x128D: i = 20;break;
		case 0x128E: i = 21;break;
		case 0x128F: i = 22;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &canopen_master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status canopen_master_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index canopen_master_firstIndex = {
  0, /* SDO_SVR */
  7, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index canopen_master_lastIndex = {
  0, /* SDO_SVR */
  22, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 canopen_master_ObjdictSize = sizeof(canopen_master_objdict)/sizeof(canopen_master_objdict[0]); 

CO_Data canopen_master_Data = CANOPEN_NODE_DATA_INITIALIZER(canopen_master);

