
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CANOPEN_MASTER_H
#define CANOPEN_MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 canopen_master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * canopen_master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data canopen_master_Data;

#endif // CANOPEN_MASTER_H
